[[mcp_servers]]
name = "unhcr-iati-mcp"
transport = "stdio"
command = "python3"
args = [
    "mcp_server.py",
]
cwd = "/home/edouard/python/unhcr_iati_mcp"
disabled_tools = []


[tools.bash]
allowlist = [
    "basename",
    "cat",
    "chmod",
    "comm",
    "cut",
    "date",
    "diff",
    "dirname",
    "du",
    "file",
    "find",
    "fmt",
    "fold",
    "grep",
    "head",
    "join",
    "less",
    "ls",
    "md5sum",
    "mkdir",
    "more",
    "nl",
    "od",
    "paste",
    "pwd",
    "readlink",
    "sha1sum",
    "sha256sum",
    "shasum",
    "sort",
    "stat",
    "sum",
    "tac",
    "tail",
    "tr",
    "uname",
    "uniq",
    "wc",
    "which",
]
